const K='ioweu-data-v1';
const uid=()=>crypto.randomUUID?crypto.randomUUID():'id_'+Date.now()+Math.random().toString(16).slice(2);
let db=load();
function load(){let d=localStorage.getItem(K);if(d)return JSON.parse(d);let n=prompt('Dein Name?')||'Ich';let x={me:{id:uid(),name:n},people:[],tx:[]};localStorage.setItem(K,JSON.stringify(x));return x}
function save(){localStorage.setItem(K,JSON.stringify(db));render()}
function money(n){return (Number(n)||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}
function tab(id){document.querySelectorAll('.view').forEach(v=>v.classList.add('hide'));document.getElementById(id).classList.remove('hide');render()}
function personName(id){if(id===db.me.id)return db.me.name;return (db.people.find(p=>p.id===id)||{}).name||'Unbekannt'}
function render(){let saldo=0;db.tx.filter(t=>t.kind==='money'&&t.status!=='rejected').forEach(t=>{if(t.creditor===db.me.id)saldo+=+t.amount;if(t.debtor===db.me.id)saldo-=+t.amount});document.getElementById('saldo').textContent=money(saldo);home();people();add();sync()}
function home(){let h='<div class=card><h2>Aktivitäten</h2>'; if(!db.tx.length)h+='<p class=mut>Noch keine Einträge.</p>'; db.tx.slice().reverse().forEach(t=>{h+=`<div class=item><b>${label(t)}</b><br><span class=pill>${t.status||'offen'}</span> <span class=mut>${t.date||''}</span><div class=actions>${t.status==='pending'?`<button onclick="setStatus('${t.id}','confirmed')">Bestätigen</button><button class="danger" onclick="setStatus('${t.id}','rejected')">Ablehnen</button>`:''}<button class=ghost onclick="exportOne('${t.id}')">Teilen</button></div></div>`});h+='</div>';document.getElementById('home').innerHTML=h}
function label(t){if(t.kind==='money')return `${personName(t.creditor)} verlieh ${personName(t.debtor)} ${money(t.amount)}`;if(t.kind==='item')return `${t.item} verliehen: ${personName(t.owner)} → ${personName(t.borrower)}`;if(t.kind==='group')return `${t.title}: ${money(t.total)} gesplittet`;return t.kind}
function people(){let h=`<div class=card><h2>Ich</h2><b>${db.me.name}</b><small>${db.me.id}</small><button class=ghost onclick="exportProfile()">Profil teilen</button></div><div class=card><h2>Freund hinzufügen</h2><input id=pn placeholder="Name"><button onclick="addPerson()">Hinzufügen</button></div><div class=card><h2>Freunde</h2>`;db.people.forEach(p=>h+=`<div class=item><b>${p.name}</b><small>${p.id}</small></div>`);h+='</div>';document.getElementById('people').innerHTML=h}
function addPerson(){let n=document.getElementById('pn').value.trim();if(!n)return;db.people.push({id:uid(),name:n});save()}
function opts(){return [db.me,...db.people].map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}
function add(){document.getElementById('add').innerHTML=`<div class=card><h2>Geld</h2><div class=row><select id=cr>${opts()}</select><select id=de>${opts()}</select></div><input id=am type=number step=.01 placeholder="Betrag"><input id=note placeholder="Notiz"><button onclick="addMoney()">Speichern</button></div><div class=card><h2>Gegenstand</h2><input id=item placeholder="z.B. Kamera"><div class=row><select id=own>${opts()}</select><select id=bor>${opts()}</select></div><button onclick="addItem()">Speichern</button></div><div class=card><h2>Gruppe splitten</h2><input id=gt placeholder="Titel"><input id=ga type=number step=.01 placeholder="Gesamtbetrag"><select id=gp>${opts()}</select><small>Zahler auswählen. Teilnehmer: alle gespeicherten Personen inkl. dir.</small><button onclick="addGroup()">Split erzeugen</button></div>`}
function base(kind){return{id:uid(),kind,date:new Date().toISOString().slice(0,10),status:'pending'}}
function addMoney(){let t={...base('money'),creditor:cr.value,debtor:de.value,amount:am.value,note:note.value};db.tx.push(t);save();tab('home')}
function addItem(){db.tx.push({...base('item'),item:item.value||'Gegenstand',owner:own.value,borrower:bor.value});save();tab('home')}
function addGroup(){let ps=[db.me,...db.people], total=+ga.value||0, payer=gp.value, share=total/ps.length;db.tx.push({...base('group'),title:gt.value||'Gruppenausgabe',total,payer,participants:ps.map(p=>p.id)});ps.filter(p=>p.id!==payer).forEach(p=>db.tx.push({...base('money'),creditor:payer,debtor:p.id,amount:share,note:'Anteil '+(gt.value||'Gruppe')}));save();tab('home')}
function setStatus(id,s){let t=db.tx.find(x=>x.id===id);if(t){t.status=s;save()}}
function pack(obj){return 'IOWEU:'+btoa(unescape(encodeURIComponent(JSON.stringify(obj))))}
function unpack(s){s=s.trim();if(s.startsWith('IOWEU:'))s=s.slice(6);return JSON.parse(decodeURIComponent(escape(atob(s))))}
function showExport(obj){let txt=pack(obj);document.getElementById('out').textContent=txt;document.getElementById('sharetxt').value=txt}
async function copyOut(){await navigator.clipboard.writeText(document.getElementById('sharetxt').value);alert('Kopiert')}
function exportProfile(){tab('sync');showExport({type:'profile',profile:db.me})}
function exportOne(id){tab('sync');showExport({type:'tx',tx:db.tx.find(t=>t.id===id)})}
function exportAll(){showExport({type:'full',data:db})}
function downloadExport(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([document.getElementById('sharetxt').value],{type:'text/plain'}));a.download='ioweu.ioweu';a.click()}
function importText(){try{merge(unpack(document.getElementById('in').value));alert('Importiert');save()}catch(e){alert('Import fehlgeschlagen')}}
function merge(o){if(o.type==='profile'){if(o.profile.id!==db.me.id&&!db.people.some(p=>p.id===o.profile.id))db.people.push(o.profile)}if(o.type==='tx'){if(!db.tx.some(t=>t.id===o.tx.id))db.tx.push(o.tx)}if(o.type==='full'){o.data.people?.forEach(p=>{if(p.id!==db.me.id&&!db.people.some(x=>x.id===p.id))db.people.push(p)});o.data.tx?.forEach(t=>{if(!db.tx.some(x=>x.id===t.id))db.tx.push(t)})}}
function sync(){document.getElementById('sync').innerHTML=`<div class=card><h2>Export</h2><div class=actions><button onclick="exportProfile()">Mein Profil</button><button onclick="exportAll()">Alles</button><button onclick="downloadExport()" class=ghost>Datei</button></div><textarea id=sharetxt readonly></textarea><div class=actions><button onclick="copyOut()">Kopieren</button><button class=ghost onclick="shareText()">Teilen</button></div><pre id=out></pre></div><div class=card><h2>Import</h2><textarea id=in placeholder="IOWEU-Text hier einfügen"></textarea><button onclick="importText()">Importieren</button></div>`}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.hidden=false});install.onclick=()=>deferred?.prompt();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();

async function shareText(){const txt=document.getElementById("sharetxt").value;if(navigator.share){try{await navigator.share({text:txt});return}catch(e){}}await navigator.clipboard.writeText(txt);alert("Teilen nicht verfügbar. Text wurde in die Zwischenablage kopiert.");}
